project_id = "tjahvypvfrjulnqmnhsh"

[functions.upload-resume]
verify_jwt = true

[functions.match]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.apply]
verify_jwt = true

[functions.apply-log]
verify_jwt = false

[functions.enrich-internship]
verify_jwt = false

[functions.enrich-missing]
verify_jwt = false

[functions.validate-internship-links]
verify_jwt = false