// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjahvypvfrjulnqmnhsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYWh2eXB2ZnJqdWxucW1uaHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjM4OTcsImV4cCI6MjA2OTIzOTg5N30.zjIlP04IUolT1v85D-dsuYr_S3dR8KHBGNdknamyz1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});